### ISSUE TITLE
Stop using python

### ISSUE THREAD

**Issue by SyntaxEvasion** [mystiqality/PiRapGenerator#1]
Learn golang, if you use golang for this it would make it a lot faster. I have no idea why would use python for a project like this.

**Comment by mystiqality** [comment]
Thanks for suggesting a new programming language for me to learn (even if its in a somewhat snide manner). I used Python as it's one of the few I know, with C not being one of them (only c# which is a little different + was with Unity, and Java being one I only just recently picked up). Also from just a quick few searches, the documentation on audio file manipulation seems quite sparse with none specifically stating if the library has the ability to "concatenate" audio files. I understand Python is a bad choice for this, mainly due to processing speed and memory management being basically non-existant, but I just used what I knew to make it quickly and because I'm most likely never going to use this script again. Thanks for checking out the code though!
